// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCva-uRA3wxHMiD5leXhcGML6v5QvnhTTg',
    appId: '1:63516327341:web:485de14ffdf08a76fbb524',
    messagingSenderId: '63516327341',
    projectId: 'tasksync-c066e',
    authDomain: 'tasksync-c066e.firebaseapp.com',
    storageBucket: 'tasksync-c066e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjCdosBgymK89Zw3twKrG69lYt8-gBWpU',
    appId: '1:63516327341:android:baf4c3487f541b71fbb524',
    messagingSenderId: '63516327341',
    projectId: 'tasksync-c066e',
    storageBucket: 'tasksync-c066e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJGRxIchP8TgiEt_1dafcD0MbCEw6YwaM',
    appId: '1:63516327341:ios:61db128d2d29721ffbb524',
    messagingSenderId: '63516327341',
    projectId: 'tasksync-c066e',
    storageBucket: 'tasksync-c066e.firebasestorage.app',
    iosBundleId: 'com.mobile.tasksync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJGRxIchP8TgiEt_1dafcD0MbCEw6YwaM',
    appId: '1:63516327341:ios:61db128d2d29721ffbb524',
    messagingSenderId: '63516327341',
    projectId: 'tasksync-c066e',
    storageBucket: 'tasksync-c066e.firebasestorage.app',
    iosBundleId: 'com.mobile.tasksync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCva-uRA3wxHMiD5leXhcGML6v5QvnhTTg',
    appId: '1:63516327341:web:0075c501aaa47098fbb524',
    messagingSenderId: '63516327341',
    projectId: 'tasksync-c066e',
    authDomain: 'tasksync-c066e.firebaseapp.com',
    storageBucket: 'tasksync-c066e.firebasestorage.app',
  );
}
